version: '3.4'

services:
  device-registry:
    build: .
    image: home-automation-device-registry
    volumes:
      - .:/usr/src/app
    ports:
      - "5001:80"
    environment:
      APP_CONFIG_FILE: /usr/src/app/config/development.py
    working_dir: /usr/src/app
